#!/bin/bash

if ! pacman -Si $1 >&/dev/null; then
    cd $HOME
    echo '+-------------------------------------------+'
    echo '|==> package not found in the official repos|'
    echo '|==> searching it in the AUR                |'
    echo '+-------------------------------------------+'
    mkdir $1 && echo "$1 directory created"
   	cd $1
    pwd
    pkg=$1.tar.gz
    if ! wget /https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz ; then
        pkg=$1-git.tar.gz
        if ! wget https://aur.archlinux.org/cgit/aur.git/snapshot/$1-git.tar.gz ; then
            echo '==> package not found'
        fi
    else
        tar -xvf $pkg
        dir=$1
        cd $dir
		if makepkg -sic ; then
			echo '==> installation complete'
		else
			echo '==> installation failed'
		fi
    fi
    cd $HOME
    rm -rf $1
else
    sudo pacman -S $1
fi
exit
