#!/bin/bash
clear
loadkeys it
echo CIAO,VUOI INSTALLARE ARCH?
read ans

if [[ $ans == y ]] || [[ $ans == yes ]] || [[ $ans == '' ]]; then
	echo hai partizionato?
	read ans
	while [ $ans == n ] || [ $ans == no ] 
       	do
		sudo fdisk -l  
		echo scegli il device 
		read dev
		if ! sudo cfdisk $dev ; then
			sudo cfdisk /dev/$dev	
		fi
		sudo fdisk -l
		echo vanno bene le partizioni?
		read ans
	done
	clear
	fdisk -l
	echo scegli la partizione di root
	read root
	if ! mkfs.ext4 /dev/$root >&/dev/null; then mkfs.ext4 $root; fi
	if ! mount /dev/$root /mnt >&/dev/null; then mount $root /mnt; fi
	clear
	fdisk -l
	echo vuoi installare /home in una partizione separata?
	read ans
	if [[ $ans == y ]] || [[ $ans == yes ]] || [[ $ans == '' ]]; then
		echo scegli partizione 
		read home
		echo vuoi formattarla?
		read ans
		if [[ $ans == y ]] || [[ $ans == yes ]] || [[ $ans == '' ]]; then
			if ! mkfs.ext4 /dev/$home >&/dev/null; then
				mkfs.ext4 $home
				mkdir /mnt/home
				mount $home /mnt/home
			else
				mkdir /mnt/home
				mount /dev/$home /mnt/home
			fi
		else
			mkdir /mnt/home
			if ! mount /dev/$home /mnt/home; then mount $home /mnt/home; fi
		fi
	fi
	clear
	fdisk -l
	echo vuoi montare /boot in una partizione separata?
	read ans
	if [[ $ans == 'y' ]] || [[ $ans == 'yes' ]] || [[ $ans == '' ]]; then
		bootpart=true
		mkdir /mnt/boot
		echo scegli la partizione
		read boot
		if ! mkfs.vfat -F32 /dev/$boot >&/dev/null; then
			mkfs.vfat -F32 $boot 
		       	mount $boot /mnt/boot
		else
			mount /dev/$boot /mnt/boot
		fi
	fi
	clear
	fdisk -l
	echo hai creato una partizione swap?
	read ans
	if [[ $ans == 'y' ]] || [[ $ans == 'yes' ]] || [[ $ans == '' ]]; then 
		echo scegli la partizione
		read swap
		if ! mkswap /dev/$swap; then
			mkswap $swap
			swapon $swap
		else
			swapon /dev/$swap
		fi
	fi
	clear
	echo vuoi modificare il mirrorlist di pacman?
	read ans 
	if [[ $ans == 'y' ]] || [[ $ans == 'yes' ]] || [[ $ans == '' ]]; then nano /etc/pacman.d/mirrorlist; fi
	echo che connessione hai? wifi o ethernet? se sei in una macchina virtuale premi solamente invio
	read connection
	if [[ $connection == wifi ]]; then 
		wifi-menu
		typeinterface=wifi
	elif [[ $connection == ethernet ]]; then
		ctrl=0
		while [ $ctrl == 0 ]
		do
			ifconfig -a
			echo "scegli un' interfaccia valida"
			read interface
			ifconfig $interface up
			if ping 8.8.8.8 >&/dev/null; then
				typeinterface=eth
			fi
		done
	fi
	clear
	pacstrap /mnt base base-devel net-tools netctl dialog iw wpa_supplicant grub
	clear
	genfstab -U /mnt > /mnt/etc/fstab
	sed s/none/swap/g /mnt/etc/fstab
	clear
	wget https://raw.githubusercontent.com/allibis/mountallica/master/aurdown/aurdown.sh >&/dev/null && cp aurdown.sh /mnt/bin/aurdown >&/dev/null
	arch-chroot /mnt chmod +rwx /bin/aurdown
	echo '
	pacman -Scc --noconfirm >&/dev/null
	echo bene, inserisci una password per il root
	passwd 
	clear
	if [ -d /sys/efi/efivars ]; then
		chattr -i /boot/grub/i386-pc/core.img
		grub-install --target=i386-pc --recheck --debug --force /dev/sda
		chattr +i /boot/grub/i386-pc/core.img
	else
		grub-install --target=i386-pc --recheck --debug /dev/sda
		ctrl=1
	fi
	grub-mkconfig -o /boot/grub/grub.cfg
	clear
	echo come vuoi chiamare il sistema?
	read hostname
	echo $hostname > /etc/hostname
	clear
	echo it_IT.UTF-8 UTF-8 >> /etc/locale.gen
	locale-gen
	echo LANG=it_IT.UTF-8 >> /etc/locale.conf
	echo KEYMAP=it >> /etc/vconsole.conf
	ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime
	echo "127.0.1.1        $hostname.localdomain        $hostname" >> /etc/hosts
	clear
	if [[ $typeinterface == wifi ]] ; then 
		wifi-menu
	else 
		systemctl enable dhcpcd.service >&/dev/null
	fi
	clear
	pacman -Sy xorg-server xorg-xinit
	clear
	echo che driver video hai? INTEL, AMD O NVIDIA?
	ctrl=0
	while [ $ctrl == 0 ] 
	do
		read driver
		if [[ $driver == amd ]] || [[ $driver == AMD ]] ; then 
			pacman -S  xf86-video-ati xf86-video-amdgpu && ctrl=1
		elif [[ $driver == intel ]] || [[ $driver  == INTEL ]] ; then 
			pacman -S xf86-video-intel && ctrl=1
		elif [[ $driver == nvidia ]] || [[ $driver == NVIDIA ]] ; then 
			pacman -S xf86-video-nouveau && ctrl=1
		else 
			echo inserisci un driver valido
		fi
	done
	pacman -Scc --noconfirm >&/dev/null
	sudo pacman -S mesa
	clear
	echo che shell vuoi usare?
	ctrl=0
	while [ $ctrl == 0 ]
	do
		echo "scegli una shell dalla lista
		1=zsh
		2=fish
		3=dash
		4=korn
		*=tenere bash
		"
		read shell
		case $shell in
		1)
			aurdown zsh
			echo vuoi installare oh-my zsh?
			read ans
			if [[ $ans == y ]] || [[ $ans == yes ]] || [[ $ans == "" ]]; then
				aurdown oh-my-zsh-git
			fi 
			ctrl=1 ;;
		2)	
			aurdown fish 
			ctrl=1 ;;
		3)
			aurdown dash 
			ctrl=1 ;;
		4)
			aurdown mksh 
			ctrl=1 ;; 
		*)
			echo sei sicuro di tenere bash?
			read ans
			if [[ $ans == y ]] || [[ $ans == yes ]] || [[ $ans == "" ]] ; then
				ctrl=1
			else
				echo allora inserisci una shell
			fi
			;;
		esac
	done
	clear
	echo inserisci il nome utente 
	read name
	useradd -m $name -s /bin/$shell
	passwd $name
	clear
	echo che editor cli preferisci?
	ctrl=0
	while [ $ctrl == 0 ]
	do 
		read editor
		if pacman -S $editor; then
			echo export EDITOR=$editor >> ~/.bashrc
			ctrl=1
		else
			echo inserisci un editor valido
		fi
	done
	clear
	pacman -Scc --noconfirm >&/dev/null
	echo bene, adesso bisogna modificare il file /etc/sudoers per utilizzare sudo
	echo decommenta la riga "ALL=(ALL) ALL" per usare sudo
	echo
	echo premi invio per modificare il file
	read
	${editor} /etc/sudoers
	clear
	echo "inserisci il numero corrispondente al DE per installarlo
	1=xfce
	2=gnome
	3=kde
	4=mate
	5=deepin
	6=budgie
	7=enlightenment
	8=cinnamon
	9=lxde
	10=lxqt
	11=sugar
	"
	ctrl=0
	while [ $ctrl == 0 ]
	do
		read de
		case $de in 
		1)
	    		pacman -S xfce4 && ctrl=1 ;;
		2)
	    		pacman -S gnome && ctrl=1 ;;
		3)
	    		pacman -S plasma && ctrl=1 ;;
		4)
	    		pacman -S mate && ctrl=1 ;;
		5)
	   		pacman -S deepin && ctrl=1 ;;
		6)
	    		pacman -S budgie-desktop && ctrl=1 ;;
		7)
	    		pacman -S enlightenment && ctrl=1 ;;
		8)
			pacman -S cinnamon && ctrl=1 ;;
		9)
			pacman -S lxde lxde-gtk3 && ctrl=1 ;;
		10)
    			pacman -S lxqt && ctrl=1 ;;
		11)
    			pacman -S sugar sugar-fructosev && ctrl=1 ;;
		*)
			echo inserisci un de nella lista
		esac
	done
	pacman -Scc --noconfirm >&/dev/null
	clear
	echo "scegli un DM e scrivi il numero corrispondente
	1=lightdm
	2=sddm
	3=gdm
	4=lxdm
	5=slim
	"
	ctrl=0
	while [ $ctrl == 0 ] 
	do
		read dm
		case $dm in
		1)
			pacman -S lightdm
			systemctl enable lightdm 
			ctrl=1 ;;
		2)
			pacman -S sddm
			systemctl enable sddm 
			ctrl=1 ;;
		3)
			pacman -S gdm			
			systemctl enable gdm 
			ctrl=1 ;;
		4)
			pacman -S lxdm
			systemctl enable lxdm 
			ctrl=1 ;;
		5)
			pacman -S slim
			systemctl enable slim
			ctrl=1 ;;
		*)
			echo inserisci un numero da 1 a 6 ;;
		esac
	done
	clear
	pacman -Scc --noconfirm >&/dev/null
	echo vuoi installare altro?
	read ans
	if [[ $ans == y ]] || [[ $ans == yes ]] || [[ $ans == "" ]]; then
		ctrl=0
		echo scrivi un pacchetto alla volta, quando hai finito inserisci "end"
		while [ $ctrl == 0 ]
		do
			read pkg
			if [[ $pkg == end ]]; then
				ctrl=1
			else
				aurdown $pkg
			fi
		done
	fi
	clear' > /mnt/next.sh
	arch-chroot /mnt chmod +rx /next.sh
	arch-chroot /mnt sh /next.sh
	echo "Bene! L'installazione è finita. Vuoi spegnere il pc?"
	read ans
	if [[ $ans == 'y' ]] || [[ $ans == 'yes' ]] || [[ $ans == '' ]]; then
		poweroff
	fi
else
	echo 'okay :('
fi
exit
